version: '2.1'
services:
  rabbitmq:
    image: andrew0928/mqrpc.rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  producer:
    image: andrew0928/mqrpc.producer
    environment:
      - MQURL="amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq

  consumer:
    image: andrew0928/mqrpc.consumer
    environment:
      - MQURL="amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq

  console:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    entrypoint: ping -t 127.0.0.1

networks:
  default:
    external:
      name: nat
